# Generated by Django 5.0 on 2025-02-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_tutor_admin_admin_message_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('totalHours', models.IntegerField()),
                ('date', models.DateField()),
                ('tutorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('assignees', models.ManyToManyField(to='polls.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.event')),
                ('hourLog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.hourlog')),
            ],
        ),
    ]
