# Generated by Django 5.1.5 on 2025-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_user_prof_desc_remove_user_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_desc',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
