"""
Django settings for gostem project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = config('DEBUG', cast=bool, default=False)
DEBUG = True #UNDOOOO!!!!!! 
ALLOWED_HOSTS = []

#SITE_ID = 3


# Application definition

INSTALLED_APPS = [
    'daphne',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'gostem',
    'chats',
    'schedule',
    
    'corsheaders',  

    'channels',
    'notes',
    #OAuth apps
    "user",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    'programs',
    
]

SOCIALACCOUNT_LOGIN_ON_GET=True 


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # The following provider-specific settings will be used for all apps:
        "SCOPE": [
            'https://www.googleapis.com/auth/userinfo.profile',
            'https://www.googleapis.com/auth/userinfo.email'
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "login_required.middleware.LoginRequiredMiddleware",
]

CORS_ALLOWED_ORIGINS = [ # for development purposes, not for production - sky
    "http://localhost:3000", # frontend
    "http://127.0.0.1:8000", # backend

]

CORS_ALLOW_ALL_ORIGINS = True  # Allows all origins (for dev purposes, but NOT good for production!) - sky
CSRF_COOKIE_NAME = "csrftoken" # for dev purposes, not production - sky
CSRF_COOKIE_HTTPONLY = False # for dev purposes, not production - sky
CORS_ALLOW_CREDENTIALS = True # for dev purposes, not production -sky

ROOT_URLCONF = "gostem.urls"

# for adding a file to a note functionality (development purposes!) -sky
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# for create date and update date attributes for note functionality - sky
USE_TZ = True
TIME_ZONE = 'America/Chicago'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Adjust the path to point outside the backend directory to your frontend build folder
        'DIRS': [os.path.join(BASE_DIR, '..', 'frontend_gostem', 'build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "gostem.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",   
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'gostem_db',  # Your PostgreSQL database name
#         'USER': 'gostem_user',  # Your PostgreSQL username
#         'PASSWORD': 'gostem',  # Your PostgreSQL password
#         'HOST': 'localhost',  # Change to your DB server if remote
#         'PORT': '5432',  # Default PostgreSQL port
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/" 
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'frontend_gostem', 'build', 'static'), 
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend"
)

CSRF_TRUSTED_ORIGINS = [ # for development purposes -sky
    "http://127.0.0.1:8000",
    "http://localhost:3000",
]
ALLOWED_HOSTS = ["127.0.0.1", "localhost", '127.0.0.1:8000', 'localhost:8000'] # for development purposes -sky


LOGIN_REDIRECT_URL = "/landing-page"
#LOGIN_URL = "/"
LOGOUT_REDIRECT_URL = "/"

LOGIN_REQUIRED_IGNORE_PATHS = [
    '/$',
]



CORS_ALLOW_ALL_ORIGINS = True
# For production, specify allowed origins:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://yourdomain.com",
# ]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication', # add this if using token authentication.
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}
