# Generated by Django 5.1.5 on 2025-02-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostem', '0001_initial'),
        ('hourlog', '0001_initial_hourlog_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlog',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to='gostem.user'),
        ),
    ]
