# Generated by Django 5.1.6 on 2025-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=30)),
                ('prof_desc', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
