# Generated by Django 5.1.5 on 2025-03-15 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Assignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostem.event')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('contentType', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('authorName', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostem.program'),
        ),
    ]
