# Generated by Django 5.1.7 on 2025-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("is_recurring", models.BooleanField(default=False)),
                ("repeat_days", models.JSONField(blank=True, null=True)),
                ("repeat_until", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
