# Generated by Django 5.1.7 on 2025-03-15 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tutors",
            field=models.ManyToManyField(
                related_name="tutoring_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
