# Generated by Django 5.1.7 on 2025-03-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="program",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
