# Generated by Django 5.1.5 on 2025-02-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0005_remove_user__h_pswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=500)),
                ('authorName', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorNote', to='polls.user')),
                ('programName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programNote', to='polls.program')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='note_files/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileNotes', to='notes.note')),
            ],
        ),
    ]
