# Generated by Django 5.1.5 on 2025-02-18 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('polls', '0005_remove_user__h_pswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='authorName',
            field=models.CharField(default='Anonymous', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='programName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programNote', to='polls.program'),
        ),
    ]
