# Generated by Django 5.1.5 on 2025-02-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_authorname_alter_note_programname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='note',
            name='programName',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='notes/note_files/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='authorName',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
