# Generated by Django 5.1.5 on 2025-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_description_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='dateModified',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='isShared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='programName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
