# Generated by Django 5.1.5 on 2025-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_authorid_remove_note_programname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='files',
            field=models.ManyToManyField(blank=True, to='notes.file'),
        ),
    ]
