# Generated by Django 5.1.5 on 2025-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_attachment_delete_file_alter_note_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/note_attaches/'),
        ),
    ]
